---
- name: try failing
  hosts: myhosts
  gather_facts: false

  vars:
    my_loop_var:
      - first
      - second
      - 10
      - True
    my_conditional_var: True

  tasks:
    #- name: show value of the loop item
    #  ansible.builtin.debug:
    #    msg: this item is {{ item }}
    #  loop: "{{ my_loop_var }}"

    #- name: conditionally show something
    #  ansible.builtin.debug:
    #    msg: my_conditional_var is {{ my_conditional_var }}
    #  when: my_conditional_var == True

    - name: read contents of /tmp/test.txt
      ansible.builtin.command:
        cmd: cat /tmp/test.txt
      register: cmd_output

    - name: fail with a message
      ansible.builtin.fail:
        msg: task failed successfully
      when: "'test' in cmd_output['stdout']"
      ignore_errors: true

    - name: after expected failure
      ansible.builtin.debug:
        msg: did this task run?
...
