---
- name: show a secret var
  hosts: localhost
  gather_facts: false

  vars_files:
    - secret.yml

  tasks:
    - name: show value of secret var
      ansible.builtin.debug:
        var: secret_var
...
